# Generated by Django 4.1.6 on 2023-02-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[("", "Female"), ("", "Male")],
                default="Not informed",
                max_length=20,
            ),
        ),
    ]
